"""
Generates a per-patient PDF health summary using ReportLab.
Designed to be printed and handed to a PHC doctor.
"""
import os
import tempfile
from datetime import date
from database.queries import (
    get_patient_by_id, get_diagnoses_for_patient,
    get_all_medications_for_patient, get_adherence_last_n_days,
    parse_dropdown
)
from llm.client import call_gemma_text
from llm.prompts import PDF_SUMMARY_PROMPT


def generate_patient_pdf(patient_dropdown):
    pid = parse_dropdown(patient_dropdown)
    if not pid:
        return None, "Please select a patient."

    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib.units import cm
        from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                        Table, TableStyle, HRFlowable)
    except ImportError:
        return None, "ReportLab not installed. Run: pip install reportlab"

    patient = get_patient_by_id(pid)
    if not patient:
        return None, "Patient not found."

    diagnoses = get_diagnoses_for_patient(pid)[:3]
    medications = get_all_medications_for_patient(pid)
    adherence_logs = get_adherence_last_n_days(pid, 7)

    patient_info_str = (
        f"Name: {patient['name']}, Age: {patient['age']}, Gender: {patient['gender']}, "
        f"Village: {patient['village']}, District: {patient['district']}, "
        f"Conditions: {patient['conditions'] or 'None'}, Allergies: {patient['allergies'] or 'None'}"
    )
    diagnoses_str = "\n".join([
        f"[{d['created_at'][:10]}] Urgency: {d['urgency']}. Conditions: {d['conditions']}. Symptoms: {d['symptom_description']}"
        for d in diagnoses
    ]) or "No diagnoses recorded."
    meds_str = "\n".join([
        f"{m['name']} {m['dose']} {m['frequency']} since {m['start_date']}"
        for m in medications if m['is_active']
    ]) or "No active medications."
    logs_str = "\n".join([
        f"{l['log_date']}: {l['medication_name']} — {l['status']}"
        for l in adherence_logs
    ]) or "No adherence logs in last 7 days."

    ai_summary_prompt = PDF_SUMMARY_PROMPT.format(
        patient_info=patient_info_str,
        diagnoses=diagnoses_str,
        medications_and_adherence=f"Medications:\n{meds_str}\n\nAdherence Logs:\n{logs_str}"
    )
    ai_summary, _ = call_gemma_text(ai_summary_prompt, temperature=0.1, max_tokens=200)
    ai_summary = ai_summary or "Summary not available."

    tmp = tempfile.NamedTemporaryFile(
        suffix=".pdf", delete=False,
        prefix=f"aarogya_{patient['name'].replace(' ', '_')}_"
    )
    doc = SimpleDocTemplate(tmp.name, pagesize=A4,
                            leftMargin=2*cm, rightMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)

    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("AAROGYA — Patient Health Summary", styles['Title']))
    story.append(Paragraph(
        f"Generated: {date.today().strftime('%d %B %Y')} | For PHC Doctor Use",
        styles['Normal']
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.green))
    story.append(Spacer(1, 0.3*cm))

    story.append(Paragraph("Patient Information", styles['Heading2']))
    info_data = [
        ["Name", patient['name'], "Age", str(patient['age'])],
        ["Gender", patient['gender'], "Village", f"{patient['village']}, {patient['district']}"],
        ["Language", patient['language'], "Registered", patient['created_at'][:10]],
        ["Conditions", patient['conditions'] or "None", "Allergies", patient['allergies'] or "None"],
    ]
    info_table = Table(info_data, colWidths=[3*cm, 6*cm, 3*cm, 6*cm])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.lightgreen),
        ('BACKGROUND', (2, 0), (2, -1), colors.lightgreen),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 0.4*cm))

    story.append(Paragraph("AI-Generated Clinical Summary", styles['Heading2']))
    story.append(Paragraph(
        "<i>Auto-generated by Aarogya AI. For reference only. Not a substitute for clinical assessment.</i>",
        styles['Normal']
    ))
    story.append(Spacer(1, 0.2*cm))
    story.append(Paragraph(ai_summary, styles['Normal']))
    story.append(Spacer(1, 0.4*cm))

    if diagnoses:
        story.append(Paragraph("Recent Triage Assessments (Last 3)", styles['Heading2']))
        for d in diagnoses:
            story.append(Paragraph(f"<b>{d['created_at'][:10]}</b> — Urgency: {d['urgency']}", styles['Normal']))
            story.append(Paragraph(f"Conditions: {d['conditions']}", styles['Normal']))
            story.append(Paragraph(f"Symptoms: {d['symptom_description']}", styles['Normal']))
            story.append(Spacer(1, 0.2*cm))

    active_meds = [m for m in medications if m['is_active']]
    if active_meds:
        story.append(Paragraph("Active Medications", styles['Heading2']))
        med_data = [["Medication", "Dose", "Frequency", "Since"]]
        for m in active_meds:
            med_data.append([m['name'], m['dose'], m['frequency'], m['start_date']])
        med_table = Table(med_data, colWidths=[5*cm, 3*cm, 4*cm, 4*cm])
        med_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.green),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
        ]))
        story.append(med_table)
        story.append(Spacer(1, 0.4*cm))

    if adherence_logs:
        story.append(Paragraph("7-Day Medication Adherence", styles['Heading2']))
        adh_data = [["Date", "Medication", "Status"]]
        for l in adherence_logs:
            status_symbol = {"Took": "Took", "Missed": "Missed", "Skipped": "Skipped"}.get(l['status'], l['status'])
            adh_data.append([l['log_date'], l['medication_name'], status_symbol])
        adh_table = Table(adh_data, colWidths=[4*cm, 8*cm, 4*cm])
        adh_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.green),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ]))
        story.append(adh_table)

    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    story.append(Paragraph(
        "Aarogya is an AI triage support tool. This report does not replace clinical diagnosis. "
        "All findings should be verified by a qualified healthcare professional.",
        styles['Normal']
    ))

    doc.build(story)
    return tmp.name, None
